on:
  push:
    branches:
      - master
  schedule:
    - cron: '3 8 * * *'
name: Mirror the Github repos to Gitee
jobs:
  run:
    name: Sync-GitHub-to-Gitee
    runs-on: ubuntu-latest
    steps:
    - name: Mirror the Github repos to Gitee.
      uses: Yikun/hub-mirror-action@v0.13
      with:
        src: github/likebeta
        dst: gitee/likebeta
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token: ${{ secrets.GITEE_TOKEN }}
        account_type: user
        force_update: true
        #clone_style: "ssh"
